### ISSUE TITLE
Actividad 4

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-4-mapa-mental-edgarmauricio123#2]
ACTIVIDAD 4: Mapa Mental 
Edgar Mauricio Sarmiento Ruiz
Grupo: 1BS

![COMUNICACION-ORAL-Y-ESCRITA-1 1](https://user-images.githubusercontent.com/112227375/191613650-125bc37e-a393-4d66-bdb6-c5a2ac18adcd.png)

**Comment by YaelTrinidad** [comment]
ACT 4 MAPA MENTAL
"TIPOS DE COMUNICACIÒN"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL 17.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
